apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: endpoint-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: endpoint-reader
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: endpoint-reader
subjects:
  - kind: ServiceAccount
    name: endpoint-reader
    namespace: default
roleRef:
  kind: ClusterRole
  name: endpoint-reader
  apiGroup: rbac.authorization.k8s.io